# The config recipe.
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240520-122407-serious-jeep

# Configure language
language: en

# Configure pipeline
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.8
    ambiguity_threshold: 0.1

# Configure policies
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    # - name: TEDPolicy
    #   max_history: 5
    #   epochs: 100
    # - name: RulePolicy
