services:
  rasa_server:
    container_name: vniu-rasa
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    networks:
      - test_work

  rasa_action:
    container_name: vniu-action
    build:
      context: actions
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - 5055:5055
    networks:
      - test_work

networks:
  test_work:
    driver: bridge